<Project>
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
        <CentralPackageFloatingVersionsEnabled>true</CentralPackageFloatingVersionsEnabled>
    </PropertyGroup>
    <ItemGroup>
        <PackageVersion Include="Aspire.Hosting.Docker" Version="13.*" />
        <PackageVersion Include="Meziantou.Analyzer" Version="3.*" />
        <PackageVersion Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.*" />
        <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.*" />
        <PackageVersion Include="Microsoft.Extensions.Http" Version="10.*" />
        <PackageVersion Include="Microsoft.Extensions.Http.Resilience" Version="10.*" />
        <PackageVersion Include="Microsoft.Extensions.Options" Version="10.*" />
        <PackageVersion Include="Microsoft.Extensions.ServiceDiscovery" Version="10.*" />
        <PackageVersion Include="Microsoft.Testing.Extensions.TrxReport" Version="2.*" />
        <PackageVersion Include="ModelContextProtocol" Version="2.*" />
        <PackageVersion Include="ModelContextProtocol.AspNetCore" Version="2.*" />
        <PackageVersion Include="Moq" Version="4.*" />
        <PackageVersion Include="Moq.Analyzers" Version="0.*" />
        <PackageVersion Include="NetCord.Hosting.Services" Version="1.*-*" />
        <PackageVersion Include="NUnit" Version="4.*" />
        <PackageVersion Include="NUnit.Analyzers" Version="4.*" />
        <PackageVersion Include="NUnit3TestAdapter" Version="6.*" />
        <PackageVersion Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.*" />
        <PackageVersion Include="OpenTelemetry.Extensions.Hosting" Version="1.*" />
        <PackageVersion Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.*" />
        <PackageVersion Include="OpenTelemetry.Instrumentation.Http" Version="1.*" />
        <PackageVersion Include="OpenTelemetry.Instrumentation.Runtime" Version="1.*" />
        <PackageVersion Include="StyleCop.Analyzers" Version="1.*-*" />
    </ItemGroup>
</Project>
