<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <GenerateDocumentationFile>True</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="ModelContextProtocol.AspNetCore" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Yappr.Models\Yappr.Models.csproj" />
        <ProjectReference Include="..\Yappr.ServiceDefaults\Yappr.ServiceDefaults.csproj" />
    </ItemGroup>
</Project>
