<Project Sdk="Aspire.AppHost.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <IsAspireHost>true</IsAspireHost>
        <UserSecretsId>7d8b7a2e-2f3f-4b0e-9f9a-8e7b6c5d4a3f</UserSecretsId>
        <GenerateDocumentationFile>True</GenerateDocumentationFile>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Yappr.Discord\Yappr.Discord.csproj" />
        <ProjectReference Include="..\Yappr.Mcp.Ollama\Yappr.Mcp.Ollama.csproj" />
        <ProjectReference Include="..\Yappr.Models\Yappr.Models.csproj" IsAspireProjectResource="false" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Hosting.Docker" />
    </ItemGroup>
</Project>
